### ISSUE TITLE
Embedding `deployment_name` is Not Documented or Illustrated

### ISSUE THREAD

**Issue by martinpeck** [microsoft/rag-experiment-accelerator#346]
The default `config.json` has this section for configuring embedding models...

```json
    "embedding_models": [
        {
            "type": "sentence-transformer",
            "model_name": "all-mpnet-base-v2"
        }
    ],
```

However, if you use Azure OpenAI you need to replace `model_name` with `deployment_name` and this isn't documented anywhere in the `README.md` or hinted at elsewhere.

Failure to replace this results in the following error:

```
Traceback (most recent call last):
  File "/workspaces/rag-experiment-accelerator/01_index.py", line 8, in <module>
    run(config_directory, data_directory, filename)
  File "/workspaces/rag-experiment-accelerator/rag_experiment_accelerator/run/index.py", line 27, in run
    config = Config(config_dir, data_dir, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/rag-experiment-accelerator/rag_experiment_accelerator/config/config.py", line 70, in __new__
    cls._instance._initialize(config_dir, data_dir, filename)
  File "/workspaces/rag-experiment-accelerator/rag_experiment_accelerator/config/config.py", line 133, in _initialize
    self.embedding_models.append(EmbeddingModelFactory.create(**kwargs))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/rag-experiment-accelerator/rag_experiment_accelerator/embedding/factory.py", line 26, in create
    return AOAIEmbeddingModel(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AOAIEmbeddingModel.__init__() missing 1 required positional argument: 'deployment_name'
```

This should be better documents, and better validated, so that the error is more helpful

**Comment by joshuaphelpsms** [comment]
This is documented in the README https://github.com/microsoft/rag-experiment-accelerator?tab=readme-ov-file#description-of-embedding-models-config
